### ISSUE TITLE
Sliding window clustering

### ISSUE THREAD

**Issue by BrieucF** [HEP-FCC/k4RecCalorimeter#10]
There are two problems with the sliding window clustering at the moment:
 - [x] in rare occurrences (~%), one hits a segfault. This problem was already there in the fccedm version, stack trace attached to the issue
 - [x] the output cluster collection contains many clusters, but all of them have exactly the same information encoded
 
[SlidingWindowStackTrace.txt](https://github.com/HEP-FCC/k4RecCalorimeter/files/6647762/SlidingWindowStackTrace.txt)

**Comment by BrieucF** [comment]
The segmentation fault occurs in the treatment of the energy shared between clusters (more precisely in this line https://github.com/BrieucF/k4RecCalorimeter/blob/main/RecCalorimeter/src/components/CreateCaloClustersSlidingWindow.cpp#L264). Here is a config that reproduces it: `/afs/cern.ch/user/b/brfranco/work/public/Fellow/FCCSW/210927/LAr_scripts/FCCSW_ecal/clusteringSegFault.py`

**Comment by giovannimarchiori** [comment]
Hi @BrieucF is this issue still there? if not we can close this issue
