### ISSUE TITLE
CellPositionsHCalBarrelPhiThetaSegTool vs CellPositionsHCalPhiThetaSegTool

### ISSUE THREAD

**Issue by giovannimarchiori** [HEP-FCC/k4RecCalorimeter#112]
Do we still need CellPositionsHCalBarrelPhiThetaSegTool? It seems to be to be completely superseded by CellPositionsHCalPhiThetaSegTool and thus could be removed

Tagging @mmlynari

**Comment by mmlynari** [comment]
Hi @giovannimarchiori , indeed, we can remove CellPositionsHCalPhiThetaSegTool
